
# Set JAVA_HOME only if a Java runtime is installed.
if /usr/libexec/java_home >/dev/null 2>&1; then
  export JAVA_HOME="$(/usr/libexec/java_home)"
fi
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/jay/.lmstudio/bin"
# End of LM Studio CLI section

. "$HOME/.cargo/env"
